import { Outfit, Open_Sans } from 'next/font/google'
import './globals.css'
import ClientProvider from '@/provider/ClientProvider'
import ThemeProvider from '@/provider/ThemeProvider'
import { Toaster } from 'react-hot-toast'

const outfit = Outfit({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-outfit',
})
const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['300', '600'],
  variable: '--font-open-sans',
})

export const metadata = {
  title: 'Expense Tracker App',
  description: 'Generated by create next app',
}

const themeScript = `
    (function() {
      const savedTheme = localStorage.getItem("theme") || "light";
      document.documentElement.setAttribute("data-theme", savedTheme);
    })();
  `

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body className={`${outfit.variable} ${openSans.variable} antialiased`}>
        <ClientProvider>
          <ThemeProvider />
          <Toaster />
          {children}
        </ClientProvider>
      </body>
    </html>
  )
}
